import { ArrowLeft, ArrowRight, CalendarClock, CheckCircle2, CircleDollarSign, Clock3, UserRound } from 'lucide-react';
import type { ReactNode } from 'react';
import { Link, useParams } from 'react-router-dom';

const courseDetails = {
  canto: { title: 'Canto', intro: 'Descubra a potência, a técnica e a identidade da sua voz.', benefits: ['Desenvolvimento de respiração e apoio vocal', 'Consciência corporal e projeção', 'Construção de repertório conectado ao aluno'], objectives: ['Cantar com mais liberdade e segurança', 'Compreender recursos técnicos da voz', 'Interpretar canções com presença e intenção'] },
  teclas: { title: 'Teclas', intro: 'Piano e teclado para tocar, acompanhar e criar repertórios.', benefits: ['Coordenação e leitura musical progressiva', 'Prática de harmonia e acompanhamento', 'Repertório construído a partir dos seus interesses'], objectives: ['Tocar melodias e acompanhamentos', 'Desenvolver independência entre as mãos', 'Compreender acordes e progressões harmônicas'] },
  cordas: { title: 'Cordas', intro: 'Violão, guitarra e baixo com prática desde as primeiras aulas.', benefits: ['Técnica aplicada ao repertório', 'Ritmo, harmonia e escuta musical', 'Possibilidades para tocar sozinho ou em grupo'], objectives: ['Construir acordes, levadas e melodias', 'Ganhar fluidez no instrumento', 'Desenvolver repertório com autonomia'] },
  percussao: { title: 'Percussão', intro: 'Ritmo, coordenação e presença para sustentar cada música.', benefits: ['Coordenação motora e percepção rítmica', 'Prática de grooves e diferentes sonoridades', 'Escuta e construção de pulsação coletiva'], objectives: ['Compreender e executar ritmos', 'Desenvolver precisão e musicalidade', 'Tocar com mais confiança em conjunto'] },
  musicalizacao: { title: 'Musicalização Infantil', intro: 'Uma relação alegre, criativa e afetiva com a música desde cedo.', benefits: ['Brincadeiras, movimento e exploração sonora', 'Desenvolvimento de escuta, ritmo e imaginação', 'Experiências adequadas à fase de cada criança'], objectives: ['Criar vínculo positivo com a música', 'Experimentar sons, ritmos e instrumentos', 'Ampliar expressão, atenção e convivência'] },
  coral: { title: 'Canto Coral', intro: 'Vozes que se encontram para construir algo maior juntas.', benefits: ['Prática vocal em grupo', 'Escuta, afinação e presença coletiva', 'Repertório compartilhado e vivência de conjunto'], objectives: ['Desenvolver consciência vocal coletiva', 'Cantar em harmonia com outras vozes', 'Viver a música como experiência de comunidade'] },
} as const;

export function CourseDetailPage() {
  const { slug } = useParams();
  const course = courseDetails[slug as keyof typeof courseDetails];

  if (!course) return <CourseNotFound />;

  return <main><section className="bg-[radial-gradient(circle_at_80%_0%,rgba(141,92,192,.35),transparent_24rem),#100d17] px-6 pb-20 pt-32 text-white sm:px-10 lg:px-16"><div className="mx-auto max-w-7xl"><Link className="inline-flex items-center gap-2 text-sm font-semibold text-white/70 transition hover:text-mezzo-yellow" to="/cursos"><ArrowLeft size={17} />Todos os cursos</Link><p className="mt-9 text-xs font-bold tracking-[.2em] text-mezzo-yellow">CURSO MEZZO</p><h1 className="mt-4 font-display text-5xl font-bold leading-[.98] tracking-[-.06em] sm:text-6xl">{course.title}</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-white/75">{course.intro}</p></div></section>
    <section className="mx-auto grid max-w-7xl gap-12 px-6 py-20 sm:px-10 lg:grid-cols-[1.15fr_.85fr] lg:px-16"><div><p className="text-xs font-bold tracking-[.18em] text-mezzo-purple">SOBRE O CURSO</p><h2 className="mt-3 font-display text-4xl font-bold leading-tight tracking-[-.04em]">Aprendizado que se transforma em música.</h2><p className="mt-6 max-w-2xl leading-relaxed text-stone-600">Na MEZZO, o curso de {course.title.toLowerCase()} une técnica, prática e repertório para que cada aluno avance com sentido e confiança. O percurso é orientado pelos objetivos, experiência e ritmo de quem aprende.</p><div className="mt-10 grid gap-8 md:grid-cols-2"><InfoList title="Benefícios" items={course.benefits} /><InfoList title="Objetivos" items={course.objectives} /></div></div><aside className="rounded-2xl border border-mezzo-purple/15 bg-white p-7 shadow-sm"><h2 className="font-display text-3xl font-bold">Informações</h2><dl className="mt-5 divide-y divide-mezzo-purple/15"><Detail icon={<UserRound />} label="Professor" value="Equipe MEZZO — perfil oficial a confirmar." /><Detail icon={<CalendarClock />} label="Horários" value="Consulte a disponibilidade com a equipe." /><Detail icon={<Clock3 />} label="Modalidade" value="Formato e duração a confirmar com a escola." /><Detail icon={<CircleDollarSign />} label="Valores" value="Consulte planos e condições vigentes." /></dl><Link className="mt-7 inline-flex w-full items-center justify-center gap-2 rounded-md bg-mezzo-yellow px-4 py-3 font-bold text-mezzo-ink transition hover:bg-mezzo-yellow-light" to="/contato">Falar sobre este curso <ArrowRight size={18} /></Link></aside></section>
    <section className="bg-stone-100 px-6 py-20 sm:px-10 lg:px-16"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold tracking-[.18em] text-mezzo-purple">GALERIA DO CURSO</p><h2 className="mt-3 font-display text-4xl font-bold tracking-[-.04em]">A música acontece na prática.</h2><p className="mt-4 max-w-2xl text-stone-600">As imagens autorizadas de aulas, ensaios e apresentações de {course.title.toLowerCase()} serão publicadas aqui pela MEZZO.</p><div className="mt-8 grid gap-4 sm:grid-cols-3"><div className="min-h-52 rounded-2xl bg-[linear-gradient(145deg,#50247a,#2c1746)]" role="img" aria-label={`Espaço reservado para foto do curso de ${course.title}`} /><div className="min-h-52 rounded-2xl bg-[linear-gradient(145deg,#2c1746,#100d17)]" role="img" aria-label={`Espaço reservado para foto de aula de ${course.title}`} /><div className="min-h-52 rounded-2xl bg-[linear-gradient(145deg,#8d5cc0,#50247a)]" role="img" aria-label={`Espaço reservado para foto de apresentação de ${course.title}`} /></div></div></section>
    <section className="bg-mezzo-purple px-6 py-16 text-white sm:px-10 lg:px-16"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-5 md:flex-row md:items-center"><div><p className="text-xs font-bold tracking-[.18em] text-mezzo-yellow">PRONTO PARA COMEÇAR?</p><h2 className="mt-2 font-display text-3xl font-bold">Vamos encontrar o melhor caminho para você.</h2></div><Link className="inline-flex shrink-0 items-center gap-2 rounded-md bg-mezzo-yellow px-5 py-3 font-bold text-mezzo-ink transition hover:bg-mezzo-yellow-light" to="/contato">Quero uma orientação <ArrowRight size={18} /></Link></div></section></main>;
}

function InfoList({ items, title }: { items: readonly string[]; title: string }) {
  return <div><h3 className="font-display text-2xl font-bold">{title}</h3><ul className="mt-4 space-y-3">{items.map((item) => <li className="flex gap-2.5 text-sm leading-relaxed text-stone-600" key={item}><CheckCircle2 className="mt-0.5 shrink-0 text-mezzo-purple" size={17} aria-hidden="true" />{item}</li>)}</ul></div>;
}

function Detail({ icon, label, value }: { icon: ReactNode; label: string; value: string }) {
  return <div className="flex gap-3 py-4"><div className="mt-0.5 text-mezzo-purple">{icon}</div><div><dt className="text-sm font-bold">{label}</dt><dd className="mt-0.5 text-sm leading-relaxed text-stone-600">{value}</dd></div></div>;
}

function CourseNotFound() {
  return <main className="grid min-h-[60vh] place-items-center px-6 py-20 text-center"><div><h1 className="font-display text-4xl font-bold">Curso não encontrado.</h1><p className="mt-3 text-stone-600">Escolha uma das experiências disponíveis na MEZZO.</p><Link className="mt-6 inline-flex rounded-md bg-mezzo-purple px-5 py-3 font-bold text-white" to="/cursos">Ver cursos</Link></div></main>;
}
