import { MessageCircle, Music2 } from 'lucide-react';
import { Link } from 'react-router-dom';

const specialties = [
  ['Canto', 'C'],
  ['Piano e teclado', 'T'],
  ['Violão, guitarra e baixo', 'C'],
  ['Ritmo e percussão', 'P'],
  ['Musicalização infantil', 'M'],
  ['Coral e prática coletiva', 'CC'],
] as const;

export function TeachersPage() {
  return <main><section className="bg-[radial-gradient(circle_at_80%_0%,rgba(141,92,192,.35),transparent_24rem),#100d17] px-6 pb-20 pt-32 text-white sm:px-10 lg:px-16"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold tracking-[.2em] text-mezzo-yellow">QUEM ENSINA</p><h1 className="mt-4 font-display text-5xl font-bold leading-[.98] tracking-[-.06em] sm:text-6xl">Pessoas que fazem<br />a música acontecer.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-white/75">Professores com escuta, repertório e compromisso para acompanhar o seu desenvolvimento musical.</p></div></section><section className="mx-auto max-w-7xl px-6 py-20 sm:px-10 lg:px-16"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold tracking-[.18em] text-mezzo-purple">NOSSA EQUIPE</p><h2 className="mt-3 max-w-2xl font-display text-4xl font-bold leading-tight tracking-[-.04em] sm:text-5xl">Conhecimento que inspira confiança para criar.</h2></div><p className="max-w-md text-sm leading-relaxed text-stone-600">Os perfis oficiais serão publicados após a escola fornecer nomes, fotos autorizadas, biografias e redes sociais da equipe.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{specialties.map(([specialty, initials]) => <article className="overflow-hidden rounded-2xl border border-mezzo-purple/15 bg-white shadow-sm" key={specialty}><div className="grid aspect-[4/4.2] place-items-center bg-[linear-gradient(145deg,#50247a,#2c1746)] font-display text-5xl font-bold text-mezzo-yellow" role="img" aria-label={`Área reservada para foto do professor de ${specialty}`}>{initials}</div><div className="p-6"><h2 className="font-display text-2xl font-bold">Professor(a) de {specialty}</h2><p className="mt-2 text-xs font-bold uppercase tracking-[.1em] text-mezzo-purple">{specialty}</p><p className="mt-4 text-sm leading-relaxed text-stone-600">Formação, abordagem de ensino e canais profissionais serão inseridos após validação da equipe da MEZZO.</p><Link className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-mezzo-purple hover:underline" to="/contato"><MessageCircle size={16} />Solicitar informações</Link></div></article>)}</div></section><section className="bg-mezzo-purple px-6 py-16 text-white sm:px-10 lg:px-16"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 md:flex-row md:items-center"><div><p className="text-xs font-bold tracking-[.18em] text-mezzo-yellow">ENCONTRE SEU CURSO</p><h2 className="mt-2 font-display text-3xl font-bold">Pronto para começar a sua experiência musical?</h2></div><Link className="inline-flex items-center gap-2 rounded-md bg-mezzo-yellow px-5 py-3 font-bold text-mezzo-ink" to="/contato"><Music2 size={18} />Falar com a MEZZO</Link></div></section></main>;
}
