import { UsersRound } from 'lucide-react';
import { useEffect, useState } from 'react';

import { useAuth } from '../../auth/AuthProvider';
import { fetchLeads, type Lead, type LeadStatus, updateLeadStatus } from '../crm.api';

const statusLabels: Record<LeadStatus, string> = { NEW: 'Novo', CONTACTED: 'Contatado', TRIAL_SCHEDULED: 'Aula experimental', WON: 'Convertido', LOST: 'Perdido' };

export function CrmPage() {
  const { accessToken } = useAuth();
  const [leads, setLeads] = useState<Lead[]>();
  const [errorMessage, setErrorMessage] = useState<string>();
  useEffect(() => { if (accessToken) void fetchLeads(accessToken).then(setLeads).catch((error: unknown) => setErrorMessage(error instanceof Error ? error.message : 'Não foi possível carregar os leads.')); }, [accessToken]);
  const changeStatus = async (leadId: string, status: LeadStatus) => { if (!accessToken) return; try { await updateLeadStatus(accessToken, leadId, status); setLeads((current) => current?.map((lead) => lead.id === leadId ? { ...lead, status } : lead)); } catch (error) { setErrorMessage(error instanceof Error ? error.message : 'Não foi possível atualizar o lead.'); } };
  return <main className="px-6 py-20 lg:px-10 lg:py-10"><p className="text-xs font-bold tracking-[.18em] text-mezzo-purple">CRM</p><h1 className="mt-2 font-display text-4xl font-bold tracking-[-.04em]">Leads e oportunidades</h1><p className="mt-3 text-stone-600">Acompanhe os interesses recebidos pelo site e a evolução de cada contato.</p>{errorMessage && <p className="mt-6 rounded-md bg-red-50 p-4 text-sm font-medium text-red-800" role="alert">{errorMessage}</p>}<section className="mt-9 rounded-2xl bg-white p-7 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-bold tracking-[.16em] text-mezzo-purple">FUNIL</p><h2 className="mt-2 font-display text-3xl font-bold">Contatos recentes</h2></div><UsersRound className="text-mezzo-purple" /></div>{!leads && <p className="mt-7 text-sm text-stone-600">Carregando leads...</p>}{leads?.length === 0 && <p className="mt-7 rounded-xl border border-dashed border-mezzo-purple/25 p-8 text-center text-sm text-stone-600">Ainda não há leads cadastrados. Os interesses enviados pelo formulário público aparecerão aqui.</p>}{leads && leads.length > 0 && <div className="mt-7 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b border-mezzo-purple/15 text-xs uppercase tracking-wide text-stone-500"><tr><th className="pb-3 pr-5">Contato</th><th className="pb-3 pr-5">Interesse</th><th className="pb-3 pr-5">Origem</th><th className="pb-3 pr-5">Recebido</th><th className="pb-3">Estágio</th></tr></thead><tbody className="divide-y divide-mezzo-purple/10">{leads.map((lead) => <tr key={lead.id}><td className="py-4 pr-5"><p className="font-bold">{lead.name}</p><p className="mt-1 text-stone-600">{lead.phone ?? lead.email ?? 'Sem canal informado'}</p></td><td className="py-4 pr-5">{lead.interest ?? 'Não informado'}</td><td className="py-4 pr-5">{lead.source}</td><td className="py-4 pr-5">{formatDate(lead.createdAt)}</td><td className="py-4"><label className="sr-only" htmlFor={`status-${lead.id}`}>Estágio de {lead.name}</label><select className="rounded-md border border-mezzo-purple/20 px-2 py-1.5 font-semibold text-mezzo-purple" id={`status-${lead.id}`} value={lead.status} onChange={(event) => void changeStatus(lead.id, event.target.value as LeadStatus)}>{Object.entries(statusLabels).map(([status, label]) => <option value={status} key={status}>{label}</option>)}</select></td></tr>)}</tbody></table></div>}</section></main>;
}

function formatDate(value: string) { return new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value)); }
