import { CalendarDays, CreditCard, Music2, UserCheck } from 'lucide-react';
import type { ReactNode } from 'react';
import { useEffect, useState } from 'react';

import { useAuth } from '../../auth/AuthProvider';
import { fetchStudentOverview, type StudentOverview } from '../student.api';

export function StudentDashboardPage() {
  const { accessToken, user } = useAuth();
  const [overview, setOverview] = useState<StudentOverview>();
  const [errorMessage, setErrorMessage] = useState<string>();
  useEffect(() => { if (accessToken) void fetchStudentOverview(accessToken).then(setOverview).catch((error: unknown) => setErrorMessage(error instanceof Error ? error.message : 'Não foi possível carregar suas informações.')); }, [accessToken]);

  const attendanceRate = overview?.attendance.total ? Math.round((overview.attendance.present / overview.attendance.total) * 100) : undefined;
  return <main className="px-6 py-20 lg:px-10 lg:py-10"><p className="text-xs font-bold tracking-[.18em] text-mezzo-purple">PORTAL DO ALUNO</p><h1 className="mt-2 font-display text-4xl font-bold tracking-[-.04em]">Olá, {user?.name || user?.email}.</h1><p className="mt-3 text-stone-600">Sua agenda, evolução e informações financeiras em um só lugar.</p>{errorMessage && <p className="mt-6 rounded-md bg-red-50 p-4 text-sm font-medium text-red-800" role="alert">{errorMessage}</p>}<section className="mt-10 grid gap-4 md:grid-cols-3"><Metric icon={<CalendarDays />} label="Próximas aulas" value={overview?.upcomingLessons.length.toLocaleString() ?? '—'} /><Metric icon={<UserCheck />} label="Frequência" value={attendanceRate === undefined ? '—' : `${attendanceRate}%`} /><Metric icon={<CreditCard />} label="Faturas em aberto" value={overview?.invoices.length.toLocaleString() ?? '—'} /></section><section className="mt-8 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><article className="rounded-2xl bg-white p-7 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-bold tracking-[.16em] text-mezzo-purple">AGENDA</p><h2 className="mt-2 font-display text-3xl font-bold">Próximas aulas</h2></div><Music2 className="text-mezzo-purple" /></div>{!overview && <p className="mt-7 text-sm text-stone-600">Carregando agenda...</p>}{overview?.upcomingLessons.length === 0 && <Empty text="Quando suas próximas aulas forem agendadas, elas aparecerão aqui." />}{overview && overview.upcomingLessons.length > 0 && <ul className="mt-6 divide-y divide-mezzo-purple/10">{overview.upcomingLessons.map((lesson) => <li className="flex items-center justify-between gap-4 py-4" key={lesson.id}><div><p className="font-bold">{lesson.course}</p><p className="mt-1 text-sm text-stone-600">{lesson.teacher}{lesson.room ? ` · ${lesson.room}` : ''}</p></div><time className="text-right text-sm font-bold text-mezzo-purple" dateTime={lesson.startsAt}>{formatDate(lesson.startsAt)}<br />{formatTime(lesson.startsAt)}</time></li>)}</ul>}</article><article className="rounded-2xl bg-white p-7 shadow-sm"><p className="text-xs font-bold tracking-[.16em] text-mezzo-purple">FINANCEIRO</p><h2 className="mt-2 font-display text-3xl font-bold">Em aberto</h2>{!overview && <p className="mt-7 text-sm text-stone-600">Carregando informações...</p>}{overview?.invoices.length === 0 && <Empty text="Não há faturas pendentes no momento." />}{overview && overview.invoices.length > 0 && <ul className="mt-6 divide-y divide-mezzo-purple/10">{overview.invoices.map((invoice) => <li className="py-4" key={invoice.id}><p className="font-bold">{invoice.description}</p><div className="mt-1 flex justify-between text-sm text-stone-600"><span>Vence em {formatDate(invoice.dueDate)}</span><strong className="text-mezzo-purple">{formatCurrency(invoice.amountInCents)}</strong></div></li>)}</ul>}</article></section></main>;
}

function Metric({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <article className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex items-start justify-between"><p className="text-sm font-bold text-stone-600">{label}</p><span className="text-mezzo-purple">{icon}</span></div><p className="mt-7 font-display text-3xl font-bold">{value}</p></article>; }
function Empty({ text }: { text: string }) { return <p className="mt-7 rounded-xl border border-dashed border-mezzo-purple/25 p-6 text-center text-sm text-stone-600">{text}</p>; }
function formatCurrency(cents: number) { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(cents / 100); }
function formatDate(value: string) { return new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short' }).format(new Date(value)); }
function formatTime(value: string) { return new Intl.DateTimeFormat('pt-BR', { hour: '2-digit', minute: '2-digit' }).format(new Date(value)); }
